// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHPq221IRPNI5j6PHgvz3T8AgABOGX4Q',
    appId: '1:282015596975:web:d940e632a7f69d4ffe2f5a',
    messagingSenderId: '282015596975',
    projectId: 'hajzi-doctor',
    authDomain: 'hajzi-doctor.firebaseapp.com',
    databaseURL: 'https://hajzi-doctor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hajzi-doctor.firebasestorage.app',
    measurementId: 'G-E462R1Z9N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_25jrLIlABeJm1VrQwGw-Bc_yaRojsdk',
    appId: '1:282015596975:android:dbfa88bce4c64a3ffe2f5a',
    messagingSenderId: '282015596975',
    projectId: 'hajzi-doctor',
    databaseURL: 'https://hajzi-doctor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hajzi-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzgitWj-bPIDJHUFZp9OjRNiJlQeYFAag',
    appId: '1:282015596975:ios:cff1a97505718dc9fe2f5a',
    messagingSenderId: '282015596975',
    projectId: 'hajzi-doctor',
    databaseURL: 'https://hajzi-doctor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hajzi-doctor.firebasestorage.app',
    iosClientId: '282015596975-vl0fud7s1h865tc5jid1643mdg7ol5nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hajzi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzgitWj-bPIDJHUFZp9OjRNiJlQeYFAag',
    appId: '1:282015596975:ios:cff1a97505718dc9fe2f5a',
    messagingSenderId: '282015596975',
    projectId: 'hajzi-doctor',
    databaseURL: 'https://hajzi-doctor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hajzi-doctor.firebasestorage.app',
    iosClientId: '282015596975-vl0fud7s1h865tc5jid1643mdg7ol5nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hajzi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHPq221IRPNI5j6PHgvz3T8AgABOGX4Q',
    appId: '1:282015596975:web:cf09e032d94a0a5cfe2f5a',
    messagingSenderId: '282015596975',
    projectId: 'hajzi-doctor',
    authDomain: 'hajzi-doctor.firebaseapp.com',
    databaseURL: 'https://hajzi-doctor-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hajzi-doctor.firebasestorage.app',
    measurementId: 'G-78Q3YHFXQ4',
  );
}
